apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
  annotations:
    serving.knative.dev/visibility: "public"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      containers:
        - image: ${IMAGE}
          env:
            - name: "spring.data.mongodb.uri"
              value: ${SPRING_MONGODB_URI}
          resources:
            limits:
              memory: "512Mi"
  traffic:
    - percent: 100
      latestRevision: true